spring:
  application:
    name: tui-mobile-interview
  webflux:
    base-path: /api
  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-binding-errors=ALWAYS:

logging:
  level:
    io:
      reflectoring: INFO
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client: INFO